export const INCREMENT      = 'INCREMENT'
export const DECREMENT      = 'DECREMENT'
export const RESET          = 'RESET'
export const NOOP           = 'NOOP'
export const RANDOM         = 'RANDOM'
export const RANDOM_STORM   = 'RANDOM_STORM'
export const TOGGLE_MUTE    = 'TOGGLE_MUTE'
export const MOVE_FOCUS     = 'MOVE_FOCUS'
