export const INC  = 'INC'
export const DEC  = 'DEC'
export const RES  = 'RES'
export const NOOP = 'NOOP'
export const RAN  = 'RAN'
export const RANSTORM  = 'RANSTORM'
export const TOGGLE_MUTE  = 'TOGGLE_MUTE'
